#!/bin/bash

DOCKER_EPICS_GATEWAY=172.20.0.2
PREFIX=$PWD

exec env EPICS_CA_ADDR_LIST=$DOCKER_EPICS_GATEWAY EPICS_CA_AUTO_ADDR_LIST=NO medm -macro "prefix=${PREFIX}" -x -noMsg AUTOMEASUREMENT_OVERVIEW.adl
